### ISSUE TITLE
failing tests

### ISSUE THREAD

**Issue by captn3m0** [alexjv89/cashflowy#93]
On running app.js, I get hit with:

```
webapp_1    |   6 failing
webapp_1    | 
webapp_1    |   1) CashflowyService #findSimilarTransactions UPI payment:
webapp_1    |      TypeError: Cannot read property 'original_amount' of undefined
webapp_1    |       at Object.findSimilarTransactions (api/services/CashflowyService.js:157:37)
webapp_1    |       at Context.<anonymous> (test/services.test.js:38:48)
webapp_1    |       at process.topLevelDomainCallback (domain.js:120:23)
webapp_1    | 
webapp_1    |   2) CashflowyService #findSimilarTransactions NEFT income salary:
webapp_1    |      TypeError: Cannot read property 'original_amount' of undefined
webapp_1    |       at Object.findSimilarTransactions (api/services/CashflowyService.js:157:37)
webapp_1    |       at Context.<anonymous> (test/services.test.js:38:48)
webapp_1    |       at process.topLevelDomainCallback (domain.js:120:23)
webapp_1    | 
webapp_1    |   3) CashflowyService #findSimilarTransactions UPI incoming:
webapp_1    |      TypeError: Cannot read property 'original_amount' of undefined
webapp_1    |       at Object.findSimilarTransactions (api/services/CashflowyService.js:157:37)
webapp_1    |       at Context.<anonymous> (test/services.test.js:38:48)
webapp_1    |       at process.topLevelDomainCallback (domain.js:120:23)
webapp_1    | 
webapp_1    |   4) CashflowyService #findSimilarTransactions Netbanking outgoing:
webapp_1    |      TypeError: Cannot read property 'original_amount' of undefined
webapp_1    |       at Object.findSimilarTransactions (api/services/CashflowyService.js:157:37)
webapp_1    |       at Context.<anonymous> (test/services.test.js:38:48)
webapp_1    |       at process.topLevelDomainCallback (domain.js:120:23)
webapp_1    | 
webapp_1    |   5) CashflowyService #findSimilarTransactions Mobile banking IMPS outgoing:
webapp_1    |      TypeError: Cannot read property 'original_amount' of undefined
webapp_1    |       at Object.findSimilarTransactions (api/services/CashflowyService.js:157:37)
webapp_1    |       at Context.<anonymous> (test/services.test.js:38:48)
webapp_1    |       at process.topLevelDomainCallback (domain.js:120:23)
webapp_1    | 
webapp_1    |   6) CashflowyService #findSimilarTransactions NEFT incoming zerodha:
webapp_1    |      TypeError: Cannot read property 'original_amount' of undefined
webapp_1    |       at Object.findSimilarTransactions (api/services/CashflowyService.js:157:37)
webapp_1    |       at Context.<anonymous> (test/services.test.js:38:48)
webapp_1    |       at process.topLevelDomainCallback (domain.js:120:23)
```

This is running over Docker, but it shouldn't be related as far as I can see. I could fix this with a small fix:

```diff
 var findSimilarTransactions = function(options, callback) {
-	// console.log('this is the thing that is done');
-	var t=options.t;
+	console.log(options);
+	let t = options;
+	if (options.t) {
+		t = options.t;
+	}
```

But it failed again:

```
webapp_1    | 
webapp_1    |   1) CashflowyService #findSimilarTransactions UPI payment:
webapp_1    |      TypeError: Cannot read property 'join' of undefined
webapp_1    |       at Object.findSimilarTransactions (api/services/CashflowyService.js:167:42)
webapp_1    |       at Context.<anonymous> (test/services.test.js:38:48)
webapp_1    |       at process.topLevelDomainCallback (domain.js:120:23)
webapp_1    | 
webapp_1    |   2) CashflowyService #findSimilarTransactions NEFT income salary:
webapp_1    |      TypeError: Cannot read property 'join' of undefined
webapp_1    |       at Object.findSimilarTransactions (api/services/CashflowyService.js:167:42)
webapp_1    |       at Context.<anonymous> (test/services.test.js:38:48)
webapp_1    |       at process.topLevelDomainCallback (domain.js:120:23)
webapp_1    | 
webapp_1    |   3) CashflowyService #findSimilarTransactions UPI incoming:
webapp_1    |      TypeError: Cannot read property 'join' of undefined
webapp_1    |       at Object.findSimilarTransactions (api/services/CashflowyService.js:167:42)
webapp_1    |       at Context.<anonymous> (test/services.test.js:38:48)
webapp_1    |       at process.topLevelDomainCallback (domain.js:120:23)
webapp_1    | 
webapp_1    |   4) CashflowyService #findSimilarTransactions Netbanking outgoing:
webapp_1    |      TypeError: Cannot read property 'join' of undefined
webapp_1    |       at Object.findSimilarTransactions (api/services/CashflowyService.js:167:42)
webapp_1    |       at Context.<anonymous> (test/services.test.js:38:48)
webapp_1    |       at process.topLevelDomainCallback (domain.js:120:23)
webapp_1    | 
webapp_1    |   5) CashflowyService #findSimilarTransactions Mobile banking IMPS outgoing:
webapp_1    |      TypeError: Cannot read property 'join' of undefined
webapp_1    |       at Object.findSimilarTransactions (api/services/CashflowyService.js:167:42)
webapp_1    |       at Context.<anonymous> (test/services.test.js:38:48)
webapp_1    |       at process.topLevelDomainCallback (domain.js:120:23)
webapp_1    | 
webapp_1    |   6) CashflowyService #findSimilarTransactions NEFT incoming zerodha:
webapp_1    |      TypeError: Cannot read property 'join' of undefined
webapp_1    |       at Object.findSimilarTransactions (api/services/CashflowyService.js:167:42)
webapp_1    |       at Context.<anonymous> (test/services.test.js:38:48)
webapp_1    |       at process.topLevelDomainCallback (domain.js:120:23)
```

so I'm reporting it instead.

**Comment by aptro** [comment]
Seems like test cases are failing. Few fixtures are hard coded which won't work for other users. Will fix the issue.

**Comment by captn3m0** [comment]
Any way for me to bypass the tests while trying to run the app?

**Comment by aptro** [comment]
comment out from line no. 321 to 812 in ```test/config/services/CashflowyService.test.js```

**Comment by alexjv89** [comment]
@captn3m0, @aptro - is this resolved?

**Comment by captn3m0** [comment]
I got the app running post it, but couldn't login.

There was however this error:

```postgres_1  | 2019-02-19 19:58:08.261 UTC [31] ERROR:  relation "public.email" does not exist at character 137
postgres_1  | 2019-02-19 19:58:08.261 UTC [31] STATEMENT:  SELECT "email"."email", "email"."token", "email"."details", "email"."id", "email"."createdAt", "email"."updatedAt", "email"."user" FROM "public"."email" AS "email"  
```

migrations aren't running looks like. I didn't have time to debug further after this.

I can file a PR with my Docker Compose setup, which does make development slightly easier though.

**Comment by aptro** [comment]
@captn3m0 will look into the docker compose setup. Can you file a PR? 
There's an issue for the same https://github.com/alexjv89/cashflowy/issues/24
